version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run:
            pip install pipenv
            pipenv shell
            pipenv install
            coverage run --source='expenses/apps' manage.py test && coverage report
            COVERALLS_REPO_TOKEN=${REPO_TOKEN} coveralls
      - store_artifacts:
          path: test-reports
          destination: test-reports
