jobs:
  build:
    working_directory: ~/repo
    docker: # run the steps with Docker
      - image: circleci/python:3.6.4
        environment: # environment variables for primary container
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment: # environment variables for the Postgres container.
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py test
  lint:
    working_directory: ~/repo
    docker: 
      - image: circleci/python:3.6.4
        environment: # environment variables for primary container
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install -r requirements.txt
            flake8
  report-cov:
    docker: 
      - image: circleci/python:3.6.4
        environment: # environment variables for primary container
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install -r requirements.txt
            coverage run --source='expense_tracker/apps' manage.py test && coverage report && coverage html
            coveralls
            
workflows:
  version: 2
  build_and_lint:
    jobs:
      - build
      - lint
      - report-cov
