jobs:
  build:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run: pip install pipenv && pipenv shell
      - run: python manage.py test
workflows:
  version: 2
  build_test:
    jobs:
      - build