# Generated by Django 2.2.6 on 2019-10-19 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('spent_on', models.DateField()),
                ('payment_type', models.CharField(choices=[('VISA', 'VISA'), ('MM', 'MOBILE MONEY'), ('CASH', 'CASH')], max_length=255)),
                ('description', models.TextField(blank=True)),
                ('currency', models.CharField(default='Ugx', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
