# Generated by Django 2.2.6 on 2019-10-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('spent_on', models.DateField()),
                ('payment_type', models.CharField(choices=[('VISA', 'VISA'), ('MM', 'MOBILE MONEY'), ('CASH', 'CASH')], max_length=255)),
                ('description', models.TextField(blank=True)),
                ('currency', models.CharField(default='Ugx', max_length=20)),
            ],
        ),
    ]
