# Generated by Django 2.2.6 on 2019-10-26 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('ONLINE_SERVICES', 'ONLINE_SERVICES'), ('RENT', 'RENT'), ('BUSINESS_MISCELLENOUS', 'BUSINESS_MISCELLENOUS'), ('TRAVEL', 'TRAVEL'), ('GENERAL_MERCHANDISE', 'GENERAL_MERCHANDISE'), ('RESTUARANTS', 'ENTERTAINMENT'), ('GASOLINE_FUEL', 'GASOLINE_FUEL'), ('INSURANCE', 'INSURANCE'), ('OTHERS', 'OTHERS')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
