# Generated by Django 2.2.6 on 2019-11-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.FloatField(default='5000000.00'),
            preserve_default=False,
        ),
    ]
