# Generated by Django 2.2.6 on 2020-05-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20200509_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('ONLINE_SERVICES', 'ONLINE_SERVICES'), ('RENT', 'RENT'), ('BUSINESS_MISCELLANEOUS', 'BUSINESS_MISCELLANEOUS'), ('TRAVEL', 'TRAVEL'), ('GENERAL_MERCHANDISE', 'GENERAL_MERCHANDISE'), ('RESTUARANTS', 'RESTUARANTS'), ('ENTERTAINMENT', 'ENTERTAINMENT'), ('GASOLINE_FUEL', 'GASOLINE_FUEL'), ('INSURANCE', 'INSURANCE'), ('OTHERS', 'OTHERS')], max_length=200),
        ),
    ]
